In [1]:
import pandas as pd

In [3]:
c_path = "D:\\python\\범죄발생\\2015년_범죄발생지_지역별.csv"

In [107]:
df = pd.read_csv(c_path, engine="python")

In [108]:
dfa = df.T

In [235]:
dfb = dfa.iloc[3:-2]
dfb["지역명"] = dfb.index

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [120]:
dfb["그룹명"] = dfb.지역명.agg(lambda x: x.split(" ")[0])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [122]:
dfb[8] = dfb[8].astype(int)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [124]:
dfb[8]

서울        55280
부산        20136
대구        12759
인천        10679
광주         8438
대전         9495
울산         5449
세종          638
경기 고양      3287
경기 과천       170
경기 광명      1234
경기 광주      1072
경기 구리      1042
경기 군포       944
경기 김포      1082
경기 남양주     1888
경기 동두천      410
경기 부천      5048
경기 성남      3941
경기 수원      6487
경기 시흥      1791
경기 안산      4154
경기 안성       844
경기 안양      2142
경기 양주       719
경기 여주       417
경기 오산      1164
경기 용인      2791
경기 의왕       307
경기 의정부     2304
          ...
전북 남원       276
전북 익산      1391
전북 전주      3402
전북 정읍       565
전남 광양       461
전남 나주        46
전남 목포      1520
전남 순천      1188
전남 여수      1049
경북 경산      1174
경북 경주      1297
경북 구미      2212
경북 김천       506
경북 문경       227
경북 상주       322
경북 안동       679
경북 영주       245
경북 영천       298
경북 포항      2496
경남 거제      1395
경남 김해      2739
경남 마산         2
경남 밀양       313
경남 사천       358
경남 양산      1205
경남 진주      2032
경남 창원      5860
경남 통영       602
제주 서귀포      921
제주 제주      3309
Name: 8, Length: 86, dtype: int32

In [128]:
dfc = dfb.groupby(["그룹명"]).sum()

In [132]:
dfc.to_excel("1단계.xlsx")

In [205]:
!1단계.xlsx

In [206]:
def conv_province(i) :
    prov = i.split(" ")
    prov = prov[0]
    print(prov)
    if len(prov) == 4 and prov[-1] == "도" :
        return prov[0] + prov[2]
    else :
        return prov[0:2]

In [207]:
people_path = "D:\\python\\201612_201612_주민등록인구및세대현황_연간.csv"

In [208]:
dr = pd.read_csv(people_path, engine="python")

In [209]:
dr["그룹명"] = dr.행정구역.agg(conv_province)

전국
서울특별시
부산광역시
대구광역시
인천광역시
광주광역시
대전광역시
울산광역시
세종특별자치시
경기도
강원도
충청북도
충청남도
전라북도
전라남도
경상북도
경상남도
제주특별자치도

In [226]:
dr1 = dr.iloc[1:-1][["그룹명", "2016년_총인구수"]]
dr1.columns = ["그룹명", "all"]

In [227]:
fdf = dr1.merge(dfb, on="그룹명")

In [255]:
fdf["all"] = fdf["all"].agg(lambda x : x.replace(",","").astype(int))
fdf[8] =  fdf[8].astype(int)

In [259]:
fdf["result"] = fdf["all"]/fdf[8] * 1000

In [260]:
fdf

,그룹명,all,0,1,2,3,4,5,6,7,...,30,31,32,33,34,35,36,37,지역명,result
0,서울,9930616,67,96,274,969,118,4282,94,315,...,3941,53,74958,215,38,24,4591,41752,서울,1.796421e+05
1,부산,3498529,20,41,161,383,24,991,37,117,...,1832,198,35841,190,4,24,959,19868,부산,1.737450e+05
2,대구,2484557,13,23,60,216,21,645,20,86,...,417,19,39725,31,4,18,800,9766,대구,1.947298e+05
3,인천,2943069,17,34,103,304,35,924,31,94,...,654,69,31163,28,20,19,1200,13677,인천,2.755941e+05
4,광주,1469214,11,7,44,216,17,495,22,48,...,760,8,23412,13,3,9,371,5301,광주,1.741187e+05
5,대전,1514370,8,16,64,181,14,362,12,41,...,204,13,13556,14,4,8,630,4602,대전,1.594913e+05
6,울산,1172304,12,11,29,132,10,293,9,36,...,230,53,16600,63,2,15,382,4881,울산,2.151411e+05
7,세종,243048,2,1,-,3,1,34,-,5,...,15,2,1056,-,-,5,86,462,세종,3.809530e+05
8,경기,12716780,8,9,14,73,9,256,7,40,...,223,30,11926,13,1,4,360,3473,경기 고양,3.868810e+06
9,경기,12716780,2,-,-,-,-,20,-,1,...,6,3,720,-,-,1,10,174,경기 과천,7.480459e+07
10,경기,12716780,1,1,4,12,-,77,2,6,...,90,2,2740,6,1,3,61,1138,경기 광명,1.030533e+07
11,경기,12716780,4,8,4,25,3,49,2,6,...,87,52,3660,13,-,-,170,1135,경기 광주,1.186267e+07
12,경기,12716780,-,3,6,22,1,73,3,9,...,62,9,2151,2,-,2,71,699,경기 구리,1.220420e+07
13,경기,12716780,1,1,5,26,2,67,-,7,...,45,-,2121,4,-,-,53,672,경기 군포,1.347117e+07
14,경기,12716780,2,3,7,33,5,75,2,13,...,68,14,3726,4,-,3,50,1205,경기 김포,1.175303e+07
15,경기,12716780,5,6,12,50,2,132,9,26,...,261,52,4795,6,-,-,312,2361,경기 남양주,6.735583e+06
16,경기,12716780,-,3,-,6,-,36,-,1,...,20,5,954,-,-,-,44,372,경기 동두천,3.101654e+07
17,경기,12716780,7,13,25,105,12,291,7,38,...,162,14,10467,21,2,-,355,3804,경기 부천,2.519172e+06
18,경기,12716780,4,6,30,83,12,319,14,29,...,244,4,8900,9,2,2,362,3297,경기 성남,3.226790e+06
19,경기,12716780,6,7,38,157,21,425,23,40,...,368,25,14715,28,3,2,433,4856,경기 수원,1.960348e+06
20,경기,12716780,9,6,14,36,5,171,6,25,...,302,58,7830,5,-,3,228,1961,경기 시흥,7.100380e+06
21,경기,12716780,8,12,42,86,2,242,6,30,...,134,29,11372,26,2,1,332,3293,경기 안산,3.061334e+06
22,경기,12716780,-,2,2,23,-,42,3,4,...,51,3,2490,3,-,7,101,939,경기 안성,1.506727e+07
23,경기,12716780,2,6,7,52,4,180,4,12,...,88,5,5909,34,2,3,201,1924,경기 안양,5.936872e+06
24,경기,12716780,1,2,5,19,1,44,3,8,...,77,44,2547,5,-,1,137,847,경기 양주,1.768676e+07
25,경기,12716780,1,3,5,13,-,17,2,2,...,22,4,1687,1,-,8,19,368,경기 여주,3.049588e+07
26,경기,12716780,2,2,4,23,2,81,2,4,...,32,7,2009,1,-,-,104,913,경기 오산,1.092507e+07
27,경기,12716780,7,5,11,53,9,209,7,15,...,170,60,7716,5,2,8,235,2304,경기 용인,4.556353e+06
28,경기,12716780,-,-,1,8,-,30,-,5,...,19,5,1722,-,-,1,34,305,경기 의왕,4.142274e+07
29,경기,12716780,-,7,15,67,10,157,6,22,...,86,15,3670,5,-,-,188,1642,경기 의정부,5.519436e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,전북,1864791,-,6,7,21,2,62,4,9,...,97,15,3497,5,-,-,82,1765,전북 군산,1.268565e+06
55,전북,1864791,-,-,1,13,-,17,3,5,...,18,4,997,-,-,10,12,297,전북 김제,5.420904e+06
56,전북,1864791,-,-,2,11,1,21,-,3,...,26,3,752,3,-,6,19,255,전북 남원,6.756489e+06
57,전북,1864791,3,5,14,34,3,59,2,10,...,88,40,3202,1,-,2,55,1142,전북 익산,1.340612e+06
58,전북,1864791,4,7,21,68,4,176,6,11,...,144,11,6444,34,1,9,186,2262,전북 전주,5.481455e+05
59,전북,1864791,-,1,-,16,1,24,1,6,...,37,7,1115,2,-,7,27,401,전북 정읍,3.300515e+06
60,전남,1903914,-,3,1,14,1,19,2,3,...,15,6,2434,2,-,5,38,424,전남 광양,4.129965e+06
61,전남,1903914,-,1,-,4,1,5,1,-,...,9,2,276,-,1,6,1,140,전남 나주,4.138943e+07
62,전남,1903914,2,-,9,42,1,81,3,8,...,42,12,4699,18,1,6,98,1471,전남 목포,1.252575e+06
63,전남,1903914,1,1,9,34,5,72,3,7,...,24,5,4954,16,-,5,91,811,전남 순천,1.602621e+06
64,전남,1903914,4,2,6,43,2,51,1,13,...,78,38,5083,6,-,7,82,2846,전남 여수,1.814980e+06
65,경북,2700398,1,2,14,23,2,54,1,5,...,34,10,2464,6,1,4,82,802,경북 경산,2.300169e+06
66,경북,2700398,3,4,9,30,2,55,3,6,...,53,27,4839,3,-,9,76,1239,경북 경주,2.082034e+06
67,경북,2700398,3,2,13,50,6,81,4,10,...,118,16,8505,13,-,9,214,1307,경북 구미,1.220795e+06
68,경북,2700398,-,1,3,14,1,25,2,4,...,25,7,2121,6,-,11,37,464,경북 김천,5.336755e+06
69,경북,2700398,1,-,1,5,2,12,1,2,...,8,1,1005,-,-,3,5,190,경북 문경,1.189603e+07
70,경북,2700398,1,-,1,9,1,13,1,2,...,17,4,1160,1,-,17,32,229,경북 상주,8.386329e+06
71,경북,2700398,2,-,-,25,2,36,4,8,...,18,9,1750,6,-,2,38,532,경북 안동,3.977022e+06
72,경북,2700398,1,-,9,9,1,23,4,6,...,11,4,1644,3,-,-,14,242,경북 영주,1.102203e+07
73,경북,2700398,-,2,5,9,-,14,-,3,...,21,18,1346,-,-,3,31,268,경북 영천,9.061738e+06
74,경북,2700398,1,7,10,48,4,90,8,16,...,100,27,7475,15,-,5,243,2130,경북 포항,1.081890e+06
75,경남,3373871,2,1,4,23,2,62,1,12,...,71,19,4832,14,1,3,112,957,경남 거제,2.418546e+06
76,경남,3373871,1,7,17,42,1,114,7,9,...,126,125,8691,14,1,4,198,2018,경남 김해,1.231789e+06
77,경남,3373871,-,-,-,-,-,1,-,-,...,1,-,2,-,-,-,1,12,경남 마산,1.686936e+09
78,경남,3373871,1,5,1,10,1,20,1,2,...,51,19,1216,-,1,4,57,410,경남 밀양,1.077914e+07
79,경남,3373871,-,5,4,12,1,22,2,7,...,29,18,2517,1,-,5,42,1040,경남 사천,9.424221e+06
80,경남,3373871,2,6,2,35,3,59,1,9,...,57,7,3759,10,-,3,158,978,경남 양산,2.799893e+06
81,경남,3373871,4,-,13,63,1,58,4,12,...,123,20,3351,-,1,30,92,933,경남 진주,1.660370e+06
82,경남,3373871,7,13,26,85,8,172,13,33,...,258,77,12650,19,1,17,355,3643,경남 창원,5.757459e+05
83,경남,3373871,2,2,3,11,1,36,3,-,...,19,21,2936,43,-,4,52,1594,경남 통영,5.604437e+06