ModuleNotFoundError: No module named 'korea_showMap'

In [3]:
import pandas as pd

In [11]:
datafiles = [r"C:\Users\505\Downloads\상가업소_201609\상가업소_201609_01.csv",
r"C:\Users\505\Downloads\상가업소_201609\상가업소_201609_02.csv",
r"C:\Users\505\Downloads\상가업소_201609\상가업소_201609_03.csv",
r"C:\Users\505\Downloads\상가업소_201609\상가업소_201609_04.csv"]

df_list = []
for datafile in datafiles:
    df = pd.read_csv(datafile, engine="python")
    dfa = df[["상호명", "시도명", "시군구명"]][df.상호명.notnull() & df.상호명.str.contains("치킨")]
    df_list.append(dfa)
dfa = pd.concat(df_list)
dfb = dfa.groupby(["시도명", "시군구명"]).count()
dfb = dfb.reset_index()
dfb.to_excel("korea_blockmap.xlsx")

In [20]:
csv = r"korean_map\data_draw_korea.csv"
m = pd.read_csv(csv, encoding="utf-8", engine="python")
print(m[m.행정구역.str.contains("성남")])
print(dfb[dfb.시군구명.str.contains("성남")])

dfb["시군구명_정제"] = dfb.시군구명.agg(lambda x: x.split(" ")[0])
dfc = dfb.groupby(['시도명', "시군구명_정제"]).sum();
dfc = dfc.reset_index()
print(dfc[dfc.시군구명_정제.str.contains("성남")])

    Unnamed: 0     인구수 shortName  x  y      면적 광역시도 행정구역
29          29  911628        성남  7  8  141.82  경기도  성남시
    시도명     시군구명  상호명 시군구명_정제
33  경기도  성남시 분당구  224     성남시
34  경기도  성남시 수정구  126     성남시
35  경기도  성남시 중원구  190     성남시
                 상호명
시도명     시군구명_정제
강원도     강릉시      164
        고성군       34
        동해시       97
        삼척시       63
        속초시       98
        양구군       23
        양양군       39
        영월군       28
        원주시      279
        인제군       37
        정선군       42
        철원군       47
        춘천시      229
        태백시       41
        평창군       42
        홍천군       72
        화천군       33
        횡성군       36
경기도     가평군       42
        고양시      691
        과천시       28
        광명시      207
        광주시      193
        구리시      139
        군포시      191
        김포시      266
        남양주시     387
        동두천시      86
        부천시      621
        성남시      540
...              ...
전라북도    정읍시       88
        진안군        9
제주특별자치도 서귀포시     123
        제주시      316
충청남도    계룡시       27
        공주시       96
        금산군       35
        논산시      121
        당진시      139
        보령시      119
        부여군       51
        서산시      135
        서천군       44
        아산시      248
        예산군       63
        천안시      593
        청양군       24
        태안군       55
        홍성군       75
충청북도    괴산군       29
        단양군       31
        보은군       18
        영동군       35
        옥천군       47
        음성군       84
        제천시      133
        증평군       32
        진천군       80
        청주시      703
        충주시      220

[229 rows x 1 columns]

AttributeError: 'DataFrame' object has no attribute '시군구명_정제'

        시도명     시군구명  상호명
0       강원도      화천군    1
1       경기도      광주시    1
2       경기도      시흥시    2
3       경기도      화성시    1
4      경상남도      거제시    1
5      경상남도      김해시    1
6      경상남도      진주시    1
7      경상남도      통영시    1
8      경상남도      함안군    1
9      경상북도      고령군    1
10     경상북도      구미시    1
11     경상북도      의성군    1
12     경상북도   포항시 남구    1
13     경상북도   포항시 북구    1
14    광주광역시       북구    1
15    대구광역시      달서구    2
16    대구광역시       동구    1
17    대구광역시       북구    1
18    대구광역시      수성구    1
19    대전광역시      유성구    1
20    부산광역시     부산진구    1
21    부산광역시      사하구    1
22    부산광역시     해운대구    1
23    서울특별시      강동구    1
24  세종특별자치시  세종특별자치시    1
25    인천광역시      연수구    1
26     전라남도      무안군    1
27     충청남도      아산시    2
28     충청남도      태안군    1
29     충청북도      제천시    1
30     충청북도  청주시 흥덕구    1